### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by darkdarcool** [RayhanADev/REPLangs#1]
This is just a suggestion, but maybe you could generate a website (like a small webpage) with the data(or a json file will be generated that could be used). I would love that, this is cool af!

**Comment by RayhanADev** [comment]
~~sorry I completely forgot this comment~~
Hmmm I could make a website, I was just completely lazy with this. Maybe I could use Chart.js?

**Comment by darkdarcool** [comment]
yea, and it doesn't have to be a good or fancy website, just a small auto generated one that has a little json?

**Comment by RayhanADev** [comment]
Gotcha
